# Generated by Django 3.1.7 on 2021-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadir',
            name='lokasi',
        ),
        migrations.AddField(
            model_name='hadir',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='hadir',
            name='lat',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='hadir',
            name='lng',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
