# Generated by Django 3.1.7 on 2021-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0002_auto_20210703_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadir',
            name='city',
            field=models.CharField(default='Jakarta', max_length=50),
        ),
        migrations.AlterField(
            model_name='hadir',
            name='lat',
            field=models.CharField(default='-6.173799991607666', max_length=50),
        ),
        migrations.AlterField(
            model_name='hadir',
            name='lng',
            field=models.CharField(default='106.82669830322266', max_length=50),
        ),
    ]
