# Generated by Django 3.1.7 on 2021-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0003_auto_20210703_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadir',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
