# Generated by Django 2.2.21 on 2021-08-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0005_auto_20210816_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadir',
            name='waktu_absen',
            field=models.CharField(default='Aug. 16, 2021 , 4:08 p.m.', max_length=50),
        ),
    ]
