# Generated by Django 2.2.21 on 2021-08-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0006_hadir_waktu_absen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadir',
            name='waktu_absen',
        ),
        migrations.AddField(
            model_name='hadir',
            name='tgl',
            field=models.CharField(default='Aug. 16, 2021', max_length=50),
        ),
        migrations.AddField(
            model_name='hadir',
            name='timw',
            field=models.CharField(default='4:12 p.m', max_length=50),
        ),
    ]
