# Generated by Django 2.2.21 on 2021-08-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0007_auto_20210816_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hadir',
            old_name='timw',
            new_name='time',
        ),
    ]
