# Generated by Django 2.2.21 on 2021-11-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0008_auto_20210816_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hadir',
            old_name='nim',
            new_name='nip',
        ),
        migrations.AlterField(
            model_name='hadir',
            name='city',
            field=models.CharField(default='Jakarta', max_length=50),
        ),
        migrations.AlterField(
            model_name='hadir',
            name='lat',
            field=models.CharField(default='-6.173799991607666', max_length=50),
        ),
        migrations.AlterField(
            model_name='hadir',
            name='lng',
            field=models.CharField(default='106.82669830322266', max_length=50),
        ),
    ]
