# Generated by Django 2.2.21 on 2021-12-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0009_auto_20211117_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadir',
            name='tgl',
        ),
        migrations.RemoveField(
            model_name='hadir',
            name='time',
        ),
        migrations.AddField(
            model_name='hadir',
            name='waktu',
            field=models.DateTimeField(blank=True, default='2012-09-04 06:00:00.000000-08:00'),
        ),
    ]
