# Generated by Django 2.2.21 on 2021-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadir', '0010_auto_20211203_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadir',
            name='waktu',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
