"""
Django settings for kehadiranapp project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

if os.name == "nt":
    import platform

    # OSGEO4W = r"C:\OSGeo4W"
    # if '64' in platform.architecture()[0]:
    #     OSGEO4W += "64"
    # assert os.path.isdir(OSGEO4W), "Directory does not exist: " + OSGEO4W
    # os.environ['OSGEO4W_ROOT'] = OSGEO4W
    # os.environ['GDAL_DATA'] = OSGEO4W + r"\share\gdal"
    # os.environ['PROJ_LIB'] = OSGEO4W + r"\share\proj"
    # os.environ['PATH'] = OSGEO4W + r"\bin;" + os.environ['PATH']

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TIME_ZONE = "Asia/Bangkok"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "dwkpco446*!0rcv01*7a&a(7hn--ykvixnmc2)7#445_flw2y_"

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = []

# BARU
# DEBUG = False
# ALLOWED_HOSTS = ["127.0.0.1", "sampledomain.com"]
# BARU

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "hadir",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # baru
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    # baru
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kehadiranapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kehadiranapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True
# GDAL_LIBRARY_PATH = os.path.join(BASE_DIR,'C:\Users\Nabilah Aziz\Downloads\gdal-3.2.3\gdal-3.2.3\swig\perl\lib\Geo\GDAL')
# GEOIP_PATH = os.path.join(BASE_DIR,'hadir/geoip')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# STATIC_URL = '/static/'
# DataFlair Static Files Settings
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static-files")
# DataFlair #User_Uploaded_Files
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
